# Generated by Django 5.2.4 on 2025-08-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='summary',
        ),
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.TextField(default='Not Provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
