# Generated by Django 5.2.4 on 2025-08-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('top', 'Top News'), ('tech', 'Technology'), ('sports', 'Sports'), ('entertainment', 'Entertainment')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
